trading:
  trading_mode: simulation
  starting_portfolio:
    USDT: ${STARTING_BALANCE}
  exchanges:
    paper:
      class: simulator
      trading_pairs: [ "${PAIR}" ]
strategies:
  grid:
    enabled: true
    trading_pair: "${PAIR}"
    grid_size: 10
    grid_spacing: 0.003
    order_size: 0.001
data:
  timeframe: "${TIMEFRAME}"
logs:
  level: INFO
export:
  trades_csv: "/octobot/data/trades.csv"
